### ISSUE TITLE
Parsnip name

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [topepo/parsnip#3]
Hi Max,

Great meeting you at rstudio::conf.  So you did decide to ultimately call it `parsnip`? :-)

Cheers,
Bohdan

**Comment by topepo** [comment]
That's the name for now (since I have nothing better). I think that there is a 64% chance that it will change in the next few months =]

So basically, I'm not sure.

**Comment by Bohdan-Khomtchouk** [comment]
I don't know, it's kind of starting to grow on me to be honest :-) but I understand you're currently taking applications (so I might email you separately with some suggestions, or you could start a little voting poll ;) )

**Comment by kevinykuo** [comment]
Nominating [**daikon**](https://en.wikipedia.org/wiki/Daikon).

> 大根, literally "big root"

**Comment by topepo** [comment]
😄 

So the (reasonable) complaint is that names like these don't tell anyone what it actually does. There's plenty of counter examples (e.g. shiny, tensorflow, etc).

**Comment by johnfrombluff** [comment]
Parametric And Random Searches for Non-Informatve Priors?

Probably A Really Silly New Information Puzzle?

Predictive Analytics Reborn: Shiny New Interface for Programmers

...

Really. A name is just a moniker. It could be anything. Get over it. Shiny is the best name for a software product ever, IMNSHO. So why worry?
