### ISSUE TITLE
[Docs] Parameter Tuning

### ISSUE THREAD

**Issue by alexhallam** [topepo/parsnip#45]
I am trying to do some parameter tuning with the `ranger` engine in `parsnip`. I see that there is a `varying()` parameter, but I am confused on how to implement tuning with it. 

I really liked your tuning example [here](https://tidymodels.github.io/rsample/articles/Applications/Nested_Resampling.html) from the `rsample` package. I would benefit from documentation on how to implement this nested resampling strategy in `parsnip`.

**Comment by topepo** [comment]
>  I see that there is a `varying()` parameter, but I am confused on how to implement tuning with it.

`varying()` will only be useful when we get together the model tuning and pipeline packages. Those will be able to detect which parameters should be tuned based on if they have a `varying()` value. 

> I would benefit from documentation on how to implement this nested resampling strategy in `parsnip`.

The only goals of `parsnip` are to standardize the model api's (fit, predict, etc) and the parameter names. Given that, the only part of that tutorial that will be affected by `parsnip` are the parts that call the model fit and predict functions. 

The tuning package will have a higher level api for doing all this if you don't want to write your own `purrr` steps and so on.
