### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by grayskripko** [topepo/parsnip#47]
ERROR: dependency 'modelgenerics' is not available for package 'parsnip'

https://github.com/topepo/parsnip/blob/master/DESCRIPTION#L39
I suppose it should be replaced with "r-lib/generics"

https://github.com/topepo/parsnip/blob/master/DESCRIPTION#L24

**Comment by grayskripko** [comment]
sorry, I've missed that

**Comment by topepo** [comment]
I committed the original fix to a branch :-/
