### ISSUE TITLE
how to include data checks and/or manipulations

### ISSUE THREAD

**Issue by topepo** [topepo/parsnip#6]
For example, some functions have specific data requirements:

- some must have a matrix as input (instead of a data frame or matrix) (e.g. `glmnet`),
- want factors to be encoded as integers :-O (`tensorflow`),
- a sparse matrix is required (`xgboost`), or
- some require specific data types such as all factor predictors and so on.

Some of this could occur be modifying the default argument to the function (e.g. `x = as.matrix(x)`) but it would probably be better to include some code or module that checks or modifies the data. 

The problem is the different interfaces. We should need one for formula, recipes, and `x/y` interfaces.

**Comment by topepo** [comment]
> some must have a matrix as input (instead of a data frame or matrix) (e.g. `glmnet`)

with #12, there is a "matrix" interface that will convert `x` and `y` to matrices automatically. 

> want factors to be encoded as integers :-O (`tensorflow`)

In general, this is still an issue but for tensorflow, we will already need to have wrappers for those models. 

> a sparse matrix is required (`xgboost`), or
> some require specific data types such as all factor predictors and so on.

still unresolved.

**Comment by terrytangyuan** [comment]
Re tensorflow, I won't expect users to create models using raw tensorflow API. They would mostly just use tfestimators to create the models and tfestimators handles that factor encoding automatically (unless something changed recently).

**Comment by terrytangyuan** [comment]
For XGBoost, what do you mean by "a sparse matrix is required"? Currently sparse matrix is only optional.

**Comment by topepo** [comment]
`?xgb.train` has for `data`: 

>  input dataset. `xgb.train` takes only an `xgb.DMatrix` as the input. xgboost, in addition, also accepts matrix, `dgCMatrix`, or local data file.

Since I'm using `xgb.train`...

**Comment by topepo** [comment]
> They would mostly just use tfestimators to create the models and tfestimators handles that factor encoding automatically (unless something changed recently).

`parsnip`, at least right now, will operate on a single model call (e.g. `glm`, etc). I'll want to make small wrappers for common tensorflow (and xgboost) models that don't involve a series of function calls. The wrappers will do the required operations like making indicator variables.

**Comment by topepo** [comment]
This is handled by the interface code and the `pre`/`post` options with predictions
