### ISSUE TITLE
glmnet predictions and lambda

### ISSUE THREAD

**Issue by topepo** [topepo/parsnip#60]
We want to have the number of rows in the prediction results the same as the number of rows in `new_data`. 

Right now, the code will make predictions at _all_ lambda values contained in the model fit. Here is an example:

```r
> all_lambda <- 
+     linear_reg() %>%
+     fit(mpg ~ ., data = mtcars, engine = "glmnet")
> 
> predict(all_lambda, new_data = mtcars[1:3, -1])
# A tibble: 237 x 2
   .pred_values .pred_lambda
          <dbl>        <dbl>
 1         20.1         5.15
 2         20.1         5.15
 3         20.1         5.15
 4         20.4         4.69
 5         20.2         4.69
 6         20.5         4.69
 7         20.5         4.27
 8         20.4         4.27
 9         21.0         4.27
10         20.7         3.89
# ... with 227 more rows
> # yuk ".pred_lambda" needs to go regardless
> 
> length(unique(.Last.value$.pred_lambda))
[1] 79
```

The new `multi_predict` will generate predictions at multiple lambda values and should be preferred in this case. I suggest that 

* `predict` only produces predictions at a single lambda (and otherwise throws an error that directs people to `multi_predict` for this instance).  

* We could write some specialized predict methods for the `glmnet` subclasses (e.g. `multnet`, `lognet`, etc) that have a `penalty` argument that accepts a single value. This would _appear_ seamless to to the user since

```r
predict(all_lambda, new_data = mtcars[1:3, -1])               # errors but
predict(all_lambda, new_data = mtcars[1:3, -1], penalty = .1) # would work
```
since 

```r
> class(all_lambda)
[1] "model_fit" "_elnet"  
```

(and `predict._elnet` would just call `predict.model_fit` with a single parameter value)

**crappy straw-man alternative**: The issue is that a lot of people are going to leave `penalty` unspecified, expect to get all possible predictions back, and be frustrated that they have to use a different predict function to get them. Making `predict.model_fit` make predictions at all lambdas is possible but then it behaves differently for this model (which is how we got into this mess). 

Any other suggestions? 

<edit> fixed method dispatch

**Comment by topepo** [comment]
This was the implementation

**Comment by alexpghayes** [comment]
Didn't see this until just now, but I'm on board. Implementing along these lines in `safepredict` has cleaned some things up nicely.
