### ISSUE TITLE
fit() should use `rlang::new_environment`

### ISSUE THREAD

**Issue by DavisVaughan** [topepo/parsnip#61]
https://github.com/topepo/parsnip/blob/master/R/fit.R#L107

**Comment by DavisVaughan** [comment]
When this switch is made, arguments passed to model spec constructors will no longer work if they contain global variables or use functions from non-base packages (and potentially any package if the parent is not set to `rlang::base_env()`). This is due to the fact that, in theory, the arguments to model spec constructors are captured as expressions (to keep size low for the spec object) and then evaluated at fit time in a pristine environment that only contains things that are necessary.

This is currently complicated by the fact that `rlang::env()` is used, which is not a pristine environment, so these global vars can currently be found.

As one option, we could use the `globals` package to find global variables and functions in these argument expressions, and then include them in the pristine environment so that they can be evaluated correctly at fit time. The `future` package does this well, and uses `future::getGlobalsAndPackages()` to identify what is required for a future expression. See also `future:::MulticoreFuture()` for an example of when it assigns the actual globals to a new environment.

**Comment by topepo** [comment]
See #94.
