### ISSUE TITLE
add convenience functions that use pipe

### ISSUE THREAD

**Issue by topepo** [topepo/parsnip#77]
```r
model_spec %>% 
  add_arg(mtry = 3) %>% # maybe `set_arg` or just `arg`?
  add_arg(strata = expr(data$Attrition)) %>%
  engine("regression") # `set_engine`?
```

**Comment by DavisVaughan** [comment]
should these belong in the workflow package instead? it seems like that will be a pipe-able thing, so maybe it makes more sense to keep them there, and have parsnip hold the underlying structures that those pipe-able helpers modify
