### ISSUE TITLE
`others` should be an argument to fit

### ISSUE THREAD

**Issue by alexpghayes** [topepo/parsnip#79]
Suppose I pass some arguments that only work for `engine = "ranger"` but then set `engine = "randomForest"`. Following is an example where an argument gets silently ignored:

``` r
library(parsnip)

iris_rf <- 
  rand_forest(
    mode = "classification",
    others = list(probability = TRUE)
  ) %>%
  fit(Species ~ ., data = iris, engine = "randomForest")

set.seed(27)
x <- randomForest::randomForest(Species ~ ., data = iris)

set.seed(27)
y <- randomForest::randomForest(Species ~ ., data = iris, probability = TRUE)

testthat::expect_equivalent(x, y)
#> Error: `x` not equivalent to `y`.
#> Component "call": target, current do not match when deparsed
```

<sup>Created on 2018-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

More generally, the arguments in `others` are specific to the implementation and not properties of the random forest model itself, so I think it makes most sense for `others` to be an argument to `fit`.

**Comment by topepo** [comment]
No, arguments should only be set in the specification (otherwise it isn't a complete specification). 

We should (and previously did) do argument checking inside of `fit`.

**Comment by alexpghayes** [comment]
Not quite following. Is there an old issue thread that explains the move?

**Comment by topepo** [comment]
I think that there were already plans for the `ellipses` package to do this. Since we are using expressions and calls in `parsnip`, that package won't help here (and I don't think that was realized when I was asked to remove it).

**Comment by alexpghayes** [comment]
I meant why the specification isn't complete if `others` is an argument to `fit()` instead of the model specification constructor.

**Comment by topepo** [comment]
Because fit returns a model fit object. It has the specification also saved but the original specification object would not be the same as the one inside of the fit object.

**Comment by alexpghayes** [comment]
Okay. So the guiding principle is that `fit(model_spec, ...)` should return always return the same object for the same `model_spec` and `engine` arguments. So `model_spec` doesn't just detail the set of models, but also the estimator and any details need to get actual estimates. Following now.

**Comment by topepo** [comment]
99% of the time. There are a few minor exceptions built model-specific `translate` functions that modify the specification in there are data-driven defaults that need to be set. Since you can't set them until you see the data, they can't live in the specification. 

The translate functions can also error trap for common mistakes people make when going between two different engines. The `rand_forest` translate function does this for `importance`.
