### ISSUE TITLE
missing current_env()

### ISSUE THREAD

**Issue by grayskripko** [topepo/parsnip#92]
``` r
library(parsnip)

iris_xgboost <- boost_tree(trees = 2)

fit(
  iris_xgboost,
  Species ~ .,
  data = iris,
  engine = "xgboost"
)
#> Error in current_env(): could not find function "current_env"
```

Created on 2018-10-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by DavisVaughan** [comment]
`current_env()` is from the dev version of `rlang`. I'm not entirely sure where we use it in `parsnip` at the moment but i would try updating both the master branch of parsnip and your version of rlang. FWIW that example works for me with dev versions of both

**Comment by grayskripko** [comment]
@DavisVaughan 
Thank you for the fast response.
```current_env()``` location 
https://github.com/topepo/parsnip/blob/master/R/boost_tree.R#L312

**Comment by DavisVaughan** [comment]
Thanks! `devtools::install_github("r-lib/rlang")` should fix your problem. Be aware that `parsnip` is still highly in flux

**Comment by grayskripko** [comment]
yes, it fixed. Thanks @DavisVaughan
